// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: air_quality.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AirQuality struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceName    *string                `protobuf:"bytes,1,opt,name=device_name,json=deviceName" json:"device_name,omitempty"`
	Temp          *int32                 `protobuf:"varint,2,opt,name=temp" json:"temp,omitempty"`
	Humidity      *int64                 `protobuf:"varint,3,opt,name=humidity" json:"humidity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AirQuality) Reset() {
	*x = AirQuality{}
	mi := &file_air_quality_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AirQuality) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AirQuality) ProtoMessage() {}

func (x *AirQuality) ProtoReflect() protoreflect.Message {
	mi := &file_air_quality_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AirQuality.ProtoReflect.Descriptor instead.
func (*AirQuality) Descriptor() ([]byte, []int) {
	return file_air_quality_proto_rawDescGZIP(), []int{0}
}

func (x *AirQuality) GetDeviceName() string {
	if x != nil && x.DeviceName != nil {
		return *x.DeviceName
	}
	return ""
}

func (x *AirQuality) GetTemp() int32 {
	if x != nil && x.Temp != nil {
		return *x.Temp
	}
	return 0
}

func (x *AirQuality) GetHumidity() int64 {
	if x != nil && x.Humidity != nil {
		return *x.Humidity
	}
	return 0
}

var File_air_quality_proto protoreflect.FileDescriptor

const file_air_quality_proto_rawDesc = "" +
	"\n" +
	"\x11air_quality.proto\x12\bexamples\"]\n" +
	"\n" +
	"AirQuality\x12\x1f\n" +
	"\vdevice_name\x18\x01 \x01(\tR\n" +
	"deviceName\x12\x12\n" +
	"\x04temp\x18\x02 \x01(\x05R\x04temp\x12\x1a\n" +
	"\bhumidity\x18\x03 \x01(\x03R\bhumidityB2Z0github.com/databricks/zerobus-go-sdk/examples/pb"

var (
	file_air_quality_proto_rawDescOnce sync.Once
	file_air_quality_proto_rawDescData []byte
)

func file_air_quality_proto_rawDescGZIP() []byte {
	file_air_quality_proto_rawDescOnce.Do(func() {
		file_air_quality_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_air_quality_proto_rawDesc), len(file_air_quality_proto_rawDesc)))
	})
	return file_air_quality_proto_rawDescData
}

var file_air_quality_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_air_quality_proto_goTypes = []any{
	(*AirQuality)(nil), // 0: examples.AirQuality
}
var file_air_quality_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_air_quality_proto_init() }
func file_air_quality_proto_init() {
	if File_air_quality_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_air_quality_proto_rawDesc), len(file_air_quality_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_air_quality_proto_goTypes,
		DependencyIndexes: file_air_quality_proto_depIdxs,
		MessageInfos:      file_air_quality_proto_msgTypes,
	}.Build()
	File_air_quality_proto = out.File
	file_air_quality_proto_goTypes = nil
	file_air_quality_proto_depIdxs = nil
}
