/* Zerobus C FFI Interface */

#ifndef ZEROBUS_H
#define ZEROBUS_H

#pragma once

/* Generated with cbindgen:0.29.2 */

/* Warning: This file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
namespace zerobus {
#endif  // __cplusplus

typedef struct CZerobusSdk {
  uint8_t _private[0];
} CZerobusSdk;

typedef struct CResult {
  bool success;
  char *error_message;
  bool is_retryable;
} CResult;

typedef struct CZerobusStream {
  uint8_t _private[0];
} CZerobusStream;

typedef struct CStreamConfigurationOptions {
  uintptr_t max_inflight_records;
  bool recovery;
  uint64_t recovery_timeout_ms;
  uint64_t recovery_backoff_ms;
  uint32_t recovery_retries;
  uint64_t server_lack_of_ack_timeout_ms;
  uint64_t flush_timeout_ms;
  int32_t record_type;
} CStreamConfigurationOptions;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create a new ZerobusSdk instance
 * Returns NULL on error. Check the result parameter for error details.
 */
struct CZerobusSdk *zerobus_sdk_new(const char *zerobus_endpoint,
                                    const char *unity_catalog_url,
                                    struct CResult *result);

/**
 * Free the SDK instance
 */
void zerobus_sdk_free(struct CZerobusSdk *sdk);

/**
 * Create a stream with OAuth authentication
 * descriptor_proto_bytes: protobuf-encoded DescriptorProto (can be NULL for JSON streams)
 */
struct CZerobusStream *zerobus_sdk_create_stream(struct CZerobusSdk *sdk,
                                                 const char *table_name,
                                                 const uint8_t *descriptor_proto_bytes,
                                                 uintptr_t descriptor_proto_len,
                                                 const char *client_id,
                                                 const char *client_secret,
                                                 const struct CStreamConfigurationOptions *options,
                                                 struct CResult *result);

/**
 * Free a stream instance
 */
void zerobus_stream_free(struct CZerobusStream *stream);

/**
 * Ingest a record (protobuf encoded)
 * Returns the offset ID on success, or -1 on error
 */
int64_t zerobus_stream_ingest_proto_record(struct CZerobusStream *stream,
                                           const uint8_t *data,
                                           uintptr_t data_len,
                                           struct CResult *result);

/**
 * Ingest a JSON record
 */
int64_t zerobus_stream_ingest_json_record(struct CZerobusStream *stream,
                                          const char *json_data,
                                          struct CResult *result);

/**
 * Flush all pending records
 */
bool zerobus_stream_flush(struct CZerobusStream *stream, struct CResult *result);

/**
 * Close the stream gracefully
 */
bool zerobus_stream_close(struct CZerobusStream *stream, struct CResult *result);

/**
 * Free error message string
 */
void zerobus_free_error_message(char *message);

/**
 * Get default configuration options
 */
struct CStreamConfigurationOptions zerobus_get_default_config(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#ifdef __cplusplus
}  // namespace zerobus
#endif  // __cplusplus

#endif  /* ZEROBUS_H */
